<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Title>Access Token Validation (Owin 4) Middleware for IdentityServer3</Title>
    <Version>4.2.0-beta.3</Version>
    <Authors>Brock Allen,Dominick Baier,Stanislav</Authors>
    <Copyright>Copyright ©  2015 Dominick Baier, Brock Allen &amp; Contributors</Copyright>
    <Description>Access token validation middleware for JWT and reference tokens issued by IdentityServer3, based on JWT 5, Owin 4 and IdentityModel 3</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\default.licenseheader" Link="default.licenseheader" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityModel" Version="7.1.0" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.14.0" />
		<PackageReference Include="Microsoft.Owin.Security" Version="4.2.3" />
		<PackageReference Include="Microsoft.Owin.Security.Jwt" Version="4.2.3" />
		<PackageReference Include="System.Runtime.Caching" Version="9.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="System.Net.Http.WebRequest" />
	</ItemGroup>

</Project>
